name: NicknameManager
version: 1.0.0
description: Allows players to manage their own nicknames
authors: [TPNils]
main: be.spyproof.nickmanager.Main
softdepend: [Vault, Essentials]
commands:
  nick:
  nickname:
  admnick:
  admnickname:
  adminnickname:
  IAcceptTheNicknameRules:
